[project]
name = "FreeStream"
version = "0.1.2"
description = "Default template for PDM package"
authors = [
    {name = "Daethyra", email = "109057945+Daethyra@users.noreply.github.com"},
]
dependencies = [
    "langchain>=0.1.4",
    "streamlit>=1.30.0",
    "unstructured[all-docs]>=0.12.3",
    "sentence-transformers>=2.3.1",
    "langchain-openai>=0.0.5",
    "faiss-cpu>=1.7.4",
    "setuptools>=69.0.3",
    "langchain-google-genai>=0.0.6",
]
requires-python = ">=3.11, <3.12"
readme = "README.md"
license = {text = "GNU AGPL"}


[tool.pdm]
distribution = false

[tool.poetry]
name = ${project.name}
version = ${project.version}
description = ${project.description} 
authors = ${project.authors}

python = ${project.requires-python}

[tool.poetry.dependencies]
langchain = ${project.dependencies[0]}  
streamlit = ${project.dependencies[1]}
unstructured = {version = ${project.dependencies[2]}, extras = ["all-docs"]} 
sentence-transformers = ${project.dependencies[3]}
langchain-openai = ${project.dependencies[4]}  
faiss-cpu = ${project.dependencies[5]}
setuptools = ${project.dependencies[6]}
langchain-google-genai = ${project.dependencies[7]}

[tool.poetry.scripts]
freestream = "freestream:main"