[project]
name = "FreeStream"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Daethyra", email = "109057945+Daethyra@users.noreply.github.com"},
]
dependencies = [
    "langchain>=0.1.4",
    "streamlit>=1.30.0",
    "unstructured[all-docs]>=0.12.3",
    "langchain-google-vertexai>=0.0.3",
    "sentence-transformers>=2.3.1",
    "langchain-openai>=0.0.5",
    "faiss-cpu>=1.7.4",
]
requires-python = ">=3.11, <3.12"
readme = "README.md"
license = {text = "GNU AGPL"}


[tool.pdm]
distribution = false
