[tool.poetry]

name = "FreeStream"
version = "0.1.2"
description = "Default template for PDM package"
authors = [
    {name = "Daethyra", email = "109057945+Daethyra@users.noreply.github.com"},
]
readme = "README.md"
license = {text = "GNU AGPL"}

[tool.poetry.dependencies]

python = "^3.11",
langchain = "^0.1.4",
streamlit = "^1.30.0",
unstructured = "^0.12.3",
sentence-transformers = "^2.3.1",
langchain-openai = "^0.0.5",
faiss-cpu = "^1.7.4",
setuptools = "^69.0.3",
langchain-google-genai = "^0.0.6"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
