[tool.poetry]

name = "FreeStream"
version = "6.0.0"
description = "Streamlit chatbot template repository."
authors = ["Daethyra <109057945+Daethyra@users.noreply.github.com>"]
readme = "README.md"
license = "GNU AGPL"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"

langchain = "1.0.0a6"
streamlit = "^1.49.1"
opencv-python-headless = "^4.12.0.88"
langchain-community = "^0.3.29"
langchain-deepseek = "^0.1.4"
langgraph = "^0.6.7"
google-search-results = "^2.4.2"

[tool.poetry.group.dev.dependencies]
black = "^24.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
