[DEEPSEEK]
DEEPSEEK_API_KEY = "sk-"

[SERPAPI]
SERPAPI_KEY = ""

[LANGSMITH]
LANGSMITH_PROJECT = ""
LANGSMITH_TRACING = "true"
LANGSMITH_API_KEY = "lsv2_"
LANGSMITH_ENDPOINT = "https://api.smith.langchain.com"
